version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
      - 5000:5000
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "password"
  jenkins-selenium:
    depends_on:
      - jenkins
    build:
      context: .
      dockerfile: Dockerfile.jenkins-selenium
    container_name: jenkins-selenium
    user: root
    #entrypoint: ["bash", "wget http://jenkins:8080/jnlpJars/agent.jar /home/jenkins-selenium/agent.jar", "&&", "java", "-jar /home/jenkins-selenium/agent.jar -jnlpUrl", "http://127.0.0.1:8888/computer/selenium-agent/jenkins-agent.jnlp -workDir", "/home/jenkins-selenium"]
