version: "3"
services:
  postgres:
    image: postgres:11.10
    container_name: postgresdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:12.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/var/lib/keycloak/data
