version: "3.8"

services:
  openresty:
    image: "openresty/openresty"
    container_name: openresty
    #user: "101"
    user: "root"
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./lua_modules:/usr/local/openresty/nginx/lua_modules
        #- ./lua_modules:/usr/local/openresty/luajit/lib/lua/5.1
