version: "3.8"

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:v0.19.0
    container_name: blockbox-exporter
    privileged: true
    user: "root"
    command:
    - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
    - "./conf/blackbox.yml:/etc/blackbox/blackbox.yml"
    ports:
    - 9115:9115
