version: "3.8"

services:
  rproxy:
    image: "nginx:1.21.4"
    container_name: nginx
    user: "root"
    privileged: true
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/cert
      - ./data:/usr/share/nginx/html
