version: "3.7"

services:
  rproxy:
    image: nginx:1.19.6
    container_name: rproxy
    ports:
      - "192.168.56.5:443:443"
      - "192.168.56.5:5000:5000"
    volumes:
      - ./rproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/cert
  nexus:
    user: root
    privileged: true
    container_name: nexus3
    image: sonatype/nexus3:3.38.1
    volumes:
      - "./nexus-data:/nexus-data"
      - "./backup:/backup"
    ports:
      - "127.0.0.1:8081:8081"
#      - "5000:5000" # will use as docker registry
