services:
  gitlab:
    container_name : gitlab
    image: 'gitlab/gitlab-ce:13.6.1-ce.0'
    restart: always
    hostname: 'gitlab-server'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.openlabs.io'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['manage_backup_path'] = true
        gitlab_rails['backup_keep_time'] = 604800 # 7 days
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/cert/ssl/openlabs.io.crt"        
        nginx['ssl_certificate_key'] = "/etc/cert/ssl/openlabs.io.key"
      GITLAB_ROOT_PASSWORD: root_git
      GITLAB_TIMEZONE: Asia/Seoul
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '192.168.56.5:80:80'
      - '192.168.56.5:443:443'
      - '192.168.56.5:2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
      - './gitlab/backups:/var/opt/gitlab/backups'
