version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:jacob-custom
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
      - 5000:5000
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
      JENKINS_ADMIN_ID: "admin"
      JENKINS_ADMIN_PASSWORD: "password"
  selenium-wd:
    image: selenium/standalone-chrome:latest
    container_name: selenium-wd
    ports:
      - 4444:4444
