version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.14-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-cookie           
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit_pass
    volumes:
      - './conf/:/etc/rabbitmq/'
      - './data/:/var/lib/rabbitmq/'
